# Generated by Django 2.0.4 on 2018-04-14 22:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cycles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_brand', models.CharField(max_length=20)),
                ('cycle_type', models.CharField(max_length=10)),
                ('cycle_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=12)),
                ('hostel', models.IntegerField(validators=[django.core.validators.MaxValueValidator(13), django.core.validators.MinValueValidator(1)])),
                ('room_no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)])),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.users'),
        ),
        migrations.AddField(
            model_name='cycles',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.users'),
        ),
    ]
