# Generated by Django 2.0.2 on 2018-04-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180415_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclerequests',
            name='cycle',
            field=models.IntegerField(),
        ),
    ]
