# Generated by Django 2.0.2 on 2018-04-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180415_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclerequests',
            name='taker',
            field=models.IntegerField(),
        ),
    ]
